root = "."
tmp_dir = "tmp"

[build]
  cmd = "swag init -g cmd/main.go -o docs && go build -o ./tmp/main ./cmd/main.go"
  bin = "./tmp/main"
  stop_on_error = true
  include_ext = ["go", "tpl", "tmpl", "html", "sql", "hcl"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "internal/infra/sqlc"]
  include_dir = ["cmd", "internal"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  log = "air_errors.log"
  delay = 1000 # ms

[log]
  time = true

[misc]
  clean_on_exit = true
