services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: development
      PORT: 8888
      TZ: Asia/Tokyo
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: app
      DB_SSL_MODE: disable
      CORS_ALLOW_ORIGINS: "http://localhost:3000,http://localhost:8080"

    ports:
      - "8888:8888"
    volumes:
      - ./:/app:cached

volumes:
  pgdata:
