// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infra/repository/rating_stats.go
//
// Generated by this command:
//
//	mockgen -source=internal/infra/repository/rating_stats.go -destination=tests/mock/repository/rating_stats_mock.go -package=repositorymock
//

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	sqlc "gin-clean-starter/internal/infra/sqlc/generated"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRatingStatsQueries is a mock of RatingStatsQueries interface.
type MockRatingStatsQueries struct {
	ctrl     *gomock.Controller
	recorder *MockRatingStatsQueriesMockRecorder
	isgomock struct{}
}

// MockRatingStatsQueriesMockRecorder is the mock recorder for MockRatingStatsQueries.
type MockRatingStatsQueriesMockRecorder struct {
	mock *MockRatingStatsQueries
}

// NewMockRatingStatsQueries creates a new mock instance.
func NewMockRatingStatsQueries(ctrl *gomock.Controller) *MockRatingStatsQueries {
	mock := &MockRatingStatsQueries{ctrl: ctrl}
	mock.recorder = &MockRatingStatsQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatingStatsQueries) EXPECT() *MockRatingStatsQueriesMockRecorder {
	return m.recorder
}

// RecalcResourceRatingStats mocks base method.
func (m *MockRatingStatsQueries) RecalcResourceRatingStats(ctx context.Context, db sqlc.DBTX, resourceID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecalcResourceRatingStats", ctx, db, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecalcResourceRatingStats indicates an expected call of RecalcResourceRatingStats.
func (mr *MockRatingStatsQueriesMockRecorder) RecalcResourceRatingStats(ctx, db, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecalcResourceRatingStats", reflect.TypeOf((*MockRatingStatsQueries)(nil).RecalcResourceRatingStats), ctx, db, resourceID)
}
