// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infra/readstore/review.go
//
// Generated by this command:
//
//	mockgen -source=internal/infra/readstore/review.go -destination=tests/mock/readstore/review_mock.go -package=readstoremock
//

// Package readstoremock is a generated GoMock package.
package readstoremock

import (
	context "context"
	sqlc "gin-clean-starter/internal/infra/sqlc/generated"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockReviewViewQueries is a mock of ReviewViewQueries interface.
type MockReviewViewQueries struct {
	ctrl     *gomock.Controller
	recorder *MockReviewViewQueriesMockRecorder
	isgomock struct{}
}

// MockReviewViewQueriesMockRecorder is the mock recorder for MockReviewViewQueries.
type MockReviewViewQueriesMockRecorder struct {
	mock *MockReviewViewQueries
}

// NewMockReviewViewQueries creates a new mock instance.
func NewMockReviewViewQueries(ctrl *gomock.Controller) *MockReviewViewQueries {
	mock := &MockReviewViewQueries{ctrl: ctrl}
	mock.recorder = &MockReviewViewQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewViewQueries) EXPECT() *MockReviewViewQueriesMockRecorder {
	return m.recorder
}

// GetResourceRatingStats mocks base method.
func (m *MockReviewViewQueries) GetResourceRatingStats(ctx context.Context, db sqlc.DBTX, resourceID uuid.UUID) (sqlc.ResourceRatingStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceRatingStats", ctx, db, resourceID)
	ret0, _ := ret[0].(sqlc.ResourceRatingStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceRatingStats indicates an expected call of GetResourceRatingStats.
func (mr *MockReviewViewQueriesMockRecorder) GetResourceRatingStats(ctx, db, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceRatingStats", reflect.TypeOf((*MockReviewViewQueries)(nil).GetResourceRatingStats), ctx, db, resourceID)
}

// GetReviewViewByID mocks base method.
func (m *MockReviewViewQueries) GetReviewViewByID(ctx context.Context, db sqlc.DBTX, id uuid.UUID) (sqlc.GetReviewViewByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewViewByID", ctx, db, id)
	ret0, _ := ret[0].(sqlc.GetReviewViewByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewViewByID indicates an expected call of GetReviewViewByID.
func (mr *MockReviewViewQueriesMockRecorder) GetReviewViewByID(ctx, db, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewViewByID", reflect.TypeOf((*MockReviewViewQueries)(nil).GetReviewViewByID), ctx, db, id)
}

// GetReviewsByResourceFirstPage mocks base method.
func (m *MockReviewViewQueries) GetReviewsByResourceFirstPage(ctx context.Context, db sqlc.DBTX, arg sqlc.GetReviewsByResourceFirstPageParams) ([]sqlc.GetReviewsByResourceFirstPageRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewsByResourceFirstPage", ctx, db, arg)
	ret0, _ := ret[0].([]sqlc.GetReviewsByResourceFirstPageRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewsByResourceFirstPage indicates an expected call of GetReviewsByResourceFirstPage.
func (mr *MockReviewViewQueriesMockRecorder) GetReviewsByResourceFirstPage(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewsByResourceFirstPage", reflect.TypeOf((*MockReviewViewQueries)(nil).GetReviewsByResourceFirstPage), ctx, db, arg)
}

// GetReviewsByResourceKeyset mocks base method.
func (m *MockReviewViewQueries) GetReviewsByResourceKeyset(ctx context.Context, db sqlc.DBTX, arg sqlc.GetReviewsByResourceKeysetParams) ([]sqlc.GetReviewsByResourceKeysetRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewsByResourceKeyset", ctx, db, arg)
	ret0, _ := ret[0].([]sqlc.GetReviewsByResourceKeysetRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewsByResourceKeyset indicates an expected call of GetReviewsByResourceKeyset.
func (mr *MockReviewViewQueriesMockRecorder) GetReviewsByResourceKeyset(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewsByResourceKeyset", reflect.TypeOf((*MockReviewViewQueries)(nil).GetReviewsByResourceKeyset), ctx, db, arg)
}

// GetReviewsByUserFirstPage mocks base method.
func (m *MockReviewViewQueries) GetReviewsByUserFirstPage(ctx context.Context, db sqlc.DBTX, arg sqlc.GetReviewsByUserFirstPageParams) ([]sqlc.GetReviewsByUserFirstPageRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewsByUserFirstPage", ctx, db, arg)
	ret0, _ := ret[0].([]sqlc.GetReviewsByUserFirstPageRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewsByUserFirstPage indicates an expected call of GetReviewsByUserFirstPage.
func (mr *MockReviewViewQueriesMockRecorder) GetReviewsByUserFirstPage(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewsByUserFirstPage", reflect.TypeOf((*MockReviewViewQueries)(nil).GetReviewsByUserFirstPage), ctx, db, arg)
}

// GetReviewsByUserKeyset mocks base method.
func (m *MockReviewViewQueries) GetReviewsByUserKeyset(ctx context.Context, db sqlc.DBTX, arg sqlc.GetReviewsByUserKeysetParams) ([]sqlc.GetReviewsByUserKeysetRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewsByUserKeyset", ctx, db, arg)
	ret0, _ := ret[0].([]sqlc.GetReviewsByUserKeysetRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewsByUserKeyset indicates an expected call of GetReviewsByUserKeyset.
func (mr *MockReviewViewQueriesMockRecorder) GetReviewsByUserKeyset(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewsByUserKeyset", reflect.TypeOf((*MockReviewViewQueries)(nil).GetReviewsByUserKeyset), ctx, db, arg)
}
