// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idempotency.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys 
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context, db DBTX) (int64, error) {
	result, err := db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT 
    key,
    user_id,
    endpoint,
    request_hash,
    response_body_hash,
    status,
    result_reservation_id,
    expires_at,
    created_at,
    updated_at
FROM idempotency_keys 
WHERE key = $1 AND user_id = $2
`

type GetIdempotencyKeyParams struct {
	Key    uuid.UUID `json:"key"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, db DBTX, arg GetIdempotencyKeyParams) (IdempotencyKeys, error) {
	row := db.QueryRow(ctx, getIdempotencyKey, arg.Key, arg.UserID)
	var i IdempotencyKeys
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.Endpoint,
		&i.RequestHash,
		&i.ResponseBodyHash,
		&i.Status,
		&i.ResultReservationID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tryInsertIdempotencyKey = `-- name: TryInsertIdempotencyKey :exec
INSERT INTO idempotency_keys (
    key,
    user_id,
    endpoint,
    request_hash,
    status,
    expires_at
) VALUES (
    $1, $2, $3, $4, 'processing', $5
)
ON CONFLICT (key, user_id) DO NOTHING
`

type TryInsertIdempotencyKeyParams struct {
	Key         uuid.UUID          `json:"key"`
	UserID      uuid.UUID          `json:"user_id"`
	Endpoint    string             `json:"endpoint"`
	RequestHash string             `json:"request_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) TryInsertIdempotencyKey(ctx context.Context, db DBTX, arg TryInsertIdempotencyKeyParams) error {
	_, err := db.Exec(ctx, tryInsertIdempotencyKey,
		arg.Key,
		arg.UserID,
		arg.Endpoint,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	return err
}

const updateIdempotencyKeyCompleted = `-- name: UpdateIdempotencyKeyCompleted :exec
UPDATE idempotency_keys 
SET 
    status = 'completed',
    response_body_hash = $3,
    result_reservation_id = $4,
    updated_at = NOW()
WHERE key = $1 AND user_id = $2
`

type UpdateIdempotencyKeyCompletedParams struct {
	Key                 uuid.UUID   `json:"key"`
	UserID              uuid.UUID   `json:"user_id"`
	ResponseBodyHash    pgtype.Text `json:"response_body_hash"`
	ResultReservationID pgtype.UUID `json:"result_reservation_id"`
}

func (q *Queries) UpdateIdempotencyKeyCompleted(ctx context.Context, db DBTX, arg UpdateIdempotencyKeyCompletedParams) error {
	_, err := db.Exec(ctx, updateIdempotencyKeyCompleted,
		arg.Key,
		arg.UserID,
		arg.ResponseBodyHash,
		arg.ResultReservationID,
	)
	return err
}
