// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Companies struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Coupons struct {
	ID             uuid.UUID          `json:"id"`
	Code           string             `json:"code"`
	AmountOffCents pgtype.Int4        `json:"amount_off_cents"`
	PercentOff     pgtype.Numeric     `json:"percent_off"`
	ValidFrom      pgtype.Timestamptz `json:"valid_from"`
	ValidTo        pgtype.Timestamptz `json:"valid_to"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type IdempotencyKeys struct {
	Key                 uuid.UUID          `json:"key"`
	UserID              uuid.UUID          `json:"user_id"`
	Endpoint            string             `json:"endpoint"`
	RequestHash         string             `json:"request_hash"`
	ResponseBodyHash    pgtype.Text        `json:"response_body_hash"`
	Status              string             `json:"status"`
	ResultReservationID pgtype.UUID        `json:"result_reservation_id"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type NotificationJobs struct {
	ID        uuid.UUID          `json:"id"`
	Kind      string             `json:"kind"`
	Topic     string             `json:"topic"`
	Payload   []byte             `json:"payload"`
	RunAt     pgtype.Timestamptz `json:"run_at"`
	Attempts  int32              `json:"attempts"`
	Status    string             `json:"status"`
	LastError pgtype.Text        `json:"last_error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Reservations struct {
	ID         uuid.UUID          `json:"id"`
	ResourceID uuid.UUID          `json:"resource_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Slot       string             `json:"slot"`
	Status     string             `json:"status"`
	PriceCents int32              `json:"price_cents"`
	CouponID   pgtype.UUID        `json:"coupon_id"`
	Note       pgtype.Text        `json:"note"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Resources struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	LeadTimeMin int32              `json:"lead_time_min"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Users struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CompanyID    pgtype.UUID        `json:"company_id"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
